import {
  apiContributors,
  githubUrl,
  owner,
  repositories,
} from "@/constants/contributors";

const CarBookingConstants = {
  id: "car-booking",
  title: "RideNow - Car Booking System",
  description: "description",
  type: "Web & Mobile Application",
  imageSrc: "/projects/car-booking/car-booking.png",
  customer: "Customer",
  driver: "Driver",
  callCenter: "Call Center",
  imageListCustomer: [
    "/projects/car-booking/customer/car-booking-customer-1.png",
    "/projects/car-booking/customer/car-booking-customer-2.png",
    "/projects/car-booking/customer/car-booking-customer-3.png",
    "/projects/car-booking/customer/car-booking-customer-4.png",
    "/projects/car-booking/customer/car-booking-customer-5.png",
    "/projects/car-booking/customer/car-booking-customer-6.png",
    "/projects/car-booking/customer/car-booking-customer-7.png",
  ],
  imageListDriver: [
    "/projects/car-booking/driver/car-booking-driver-1.png",
    "/projects/car-booking/driver/car-booking-driver-2.png",
    "/projects/car-booking/driver/car-booking-driver-3.png",
  ],
  imageListCallCenter: [
    "/projects/car-booking/call-center/car-booking-callcenter-1.png",
    "/projects/car-booking/call-center/car-booking-callcenter-2.png",
    "/projects/car-booking/call-center/car-booking-callcenter-3.png",
    "/projects/car-booking/call-center/car-booking-callcenter-4.png",
    "/projects/car-booking/call-center/car-booking-callcenter-5.png",
  ],
  githubUrl: githubUrl(owner[0].name, repositories[8].name),
  apiContributors: apiContributors(owner[0].name, repositories[8].name),
  multipleGit: false,
  owner: owner[0].name,
  repository: repositories[8].name,
  techs: [
    "NodeJS",
    "ExpressJS",
    "Flutter",
    "Dart",
    "MongoDB",
    "Mongoose",
    "Material UI",
    "ReactJS",
    "S2 Geometry Algorithm",
    "RabbitMQ",
    "Design Pattern",
    "Event Driven Programming",
    "Docker",
    "Socket.IO",
  ],
  technologies: "Technologies",
  contributors: "Contributors",
};

export default CarBookingConstants;
